### ISSUE TITLE
Upgrade to Polymer 1.0

### ISSUE THREAD

**Issue by hpehl** [Jupiterrr/column-view-component#4]
In order to make it easier to use with other Web Components it would be great if you could upgrade to Polymer 1.0

**Comment by hpehl** [comment]
Just saw you opened https://github.com/Jupiterrr/column-view-component/pull/3. Can you say when you expect this to get merged into master?

**Comment by Jupiterrr** [comment]
I'm not sure, but I think it was ready, but I'll take another look. Can you test it, if its still working for you?

**Comment by hpehl** [comment]
Sure I'll give it a try and let you know whether it works.

**Comment by hpehl** [comment]
Works for me. Any schedule when this will land in master?

**Comment by Jupiterrr** [comment]
Today or tomorrow.

**Comment by Jupiterrr** [comment]
Version 0.1.0 is out.
